# Generated by Django 3.0.8 on 2021-01-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201205_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='languaje',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lenguajes'),
        ),
    ]
