# Generated by Django 3.1.5 on 2021-01-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_trajectory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='languaje',
            new_name='tecno',
        ),
    ]
