# Generated by Django 3.1.5 on 2021-01-15 20:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210113_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tecno',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated',
        ),
        migrations.AddField(
            model_name='project',
            name='tecnology',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lenguajes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
    ]
