# Generated by Django 3.1.5 on 2021-01-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20210115_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='imageOne',
            field=models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Imagen principal'),
        ),
        migrations.AddField(
            model_name='project',
            name='imageTwo',
            field=models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Imagen secundaria'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
    ]
