# Generated by Django 3.1.5 on 2021-01-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20210120_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajectory',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitulo'),
        ),
    ]
