# Generated by Django 3.1.5 on 2021-01-20 13:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20210120_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Servicios',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tecnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Tecnologías',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='trajectory',
            options={'ordering': ['-order'], 'verbose_name': 'Trayectoria'},
        ),
    ]
