# Generated by Django 3.1.5 on 2021-01-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20210120_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tecnology',
            options={'ordering': ['order'], 'verbose_name': 'Tecnología'},
        ),
    ]
