# Generated by Django 3.1.5 on 2021-01-24 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20210123_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trajectory',
            new_name='Study',
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['-order'], 'verbose_name': 'Estudios'},
        ),
        migrations.RemoveField(
            model_name='tecnology',
            name='text',
        ),
    ]
