# Generated by Django 3.1.5 on 2021-01-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20210124_0049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tecnology',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Servicio'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['-order'], 'verbose_name': 'Estudio'},
        ),
        migrations.AddField(
            model_name='project',
            name='git',
            field=models.URLField(blank=True, null=True, verbose_name='Repositorio de Git'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Atribuciones'),
        ),
    ]
