# Generated by Django 3.1.5 on 2021-01-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20210126_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.AddField(
            model_name='project',
            name='credit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Créditos'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
