# Generated by Django 3.1.5 on 2021-01-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20210126_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='der',
            field=models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Imagen principal'),
        ),
    ]
