# Generated by Django 3.1.5 on 2021-01-27 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20210126_2341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credits',
            new_name='Credit',
        ),
    ]
