# Generated by Django 3.1.5 on 2021-01-29 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_auto_20210126_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project'),
        ),
    ]
