# Generated by Django 3.1.5 on 2021-02-01 00:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_credit_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-order'], 'verbose_name': 'Proyecto'},
        ),
        migrations.AddField(
            model_name='project',
            name='dertext',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Explicación Der'),
        ),
        migrations.AlterField(
            model_name='project',
            name='der',
            field=models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Diagrama'),
        ),
    ]
